//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationTests.DatabaseResources", typeof(DatabaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE IF NOT EXISTS email_addresses (mail_id UUID,email_address VARCHAR(128),FOREIGN KEY(mail_id) REFERENCES mails(id));.
        /// </summary>
        public static string CreateEmailAddressesTable {
            get {
                return ResourceManager.GetString("CreateEmailAddressesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE IF NOT EXISTS mails (id uuid PRIMARY KEY,subject TEXT,body TEXT, date TIMESTAMP with time zone NOT NULL, result VARCHAR(16),failed_message TEXT);.
        /// </summary>
        public static string CreateMailsTable {
            get {
                return ResourceManager.GetString("CreateMailsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM email_addresses;.
        /// </summary>
        public static string DeleteEmailAddresses {
            get {
                return ResourceManager.GetString("DeleteEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM mails;  .
        /// </summary>
        public static string DeleteMails {
            get {
                return ResourceManager.GetString("DeleteMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8fd2f6fb-be46-4edf-9eff-dc93a993c856.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO email_addresses(mail_id, email_address)	VALUES (@id, &apos;first@gmail.com&apos;), (@id, &apos;second@gmail.com&apos;);.
        /// </summary>
        public static string InsertEmailAddresses {
            get {
                return ResourceManager.GetString("InsertEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO mails(id, subject, body, date, result, failed_message)VALUES(@id, &apos;test_subject&apos;, &apos;test_body&apos;, @date, &apos;test_result&apos;, &apos;test_message&apos;);.
        /// </summary>
        public static string InsertMails {
            get {
                return ResourceManager.GetString("InsertMails", resourceCulture);
            }
        }
    }
}
